### ISSUE TITLE
win10系统为什么用不了你的代码?

### ISSUE THREAD

**Issue by zhfff4869** [sincerefly/camera-detect-face#1]
Traceback (most recent call last):
  File "G:\Download\camera-detect-face\camera_detect.py", line 4, in <module>
    from gevent.wsgi import WSGIServer
ModuleNotFoundError: No module named 'gevent.wsgi'
[Finished in 1.4s]

**Comment by sincerefly** [comment]
Gevent引入wsgi方式变更

```
from gevent.wsgi import WSGIServer

修改为

from gevent.pywsgi import WSGIServer
```

参考
https://stackoverflow.com/questions/50461657/modulenotfounderror-no-module-named-gevent-wsgi

**Comment by zhfff4869** [comment]
ok 已解决，谢谢 




------------------ 原始邮件 ------------------
发件人: "Yieldone"<notifications@github.com>; 
发送时间: 2019年5月9日(星期四) 下午3:52
收件人: "sincerefly/camera-detect-face"<camera-detect-face@noreply.github.com>; 
抄送: "海峰"<1214557715@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [sincerefly/camera-detect-face] win10系统为什么用不了你的代码? (#1)




Gevent引入wsgi方式变更
 from gevent.wsgi import WSGIServer 修改为 from gevent.pywsgi import WSGIServer  
参考
 https://stackoverflow.com/questions/50461657/modulenotfounderror-no-module-named-gevent-wsgi
